/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PenentuJumlahHari;

/**
 *
 * @author stevedownes
 */
public class PenentuJumlahHari extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PenentuJumlahHari.class.getName());

    /**
     * Creates new form PenentuJumlahHari
     */
    public PenentuJumlahHari() {
        initComponents();
        
        boxBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { 
            "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" 
        }));
        
        inputTahun.setText(""); 
        outTanggal.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInput = new javax.swing.JPanel();
        boxBulan = new javax.swing.JComboBox<>();
        inputTahun = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PanelOutput = new javax.swing.JPanel();
        outTanggal = new javax.swing.JLabel();
        PanelButt = new javax.swing.JPanel();
        buttKeluar = new javax.swing.JButton();
        buttHitung = new javax.swing.JButton();
        buttDel = new javax.swing.JButton();
        buttSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelInput.setBackground(new java.awt.Color(204, 102, 0));
        PanelInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boxBulan.setBackground(new java.awt.Color(204, 204, 204));
        boxBulan.setForeground(new java.awt.Color(0, 0, 0));
        boxBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxBulanActionPerformed(evt);
            }
        });
        PanelInput.add(boxBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 240, 40));

        inputTahun.setBackground(new java.awt.Color(204, 204, 204));
        inputTahun.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        inputTahun.setForeground(new java.awt.Color(0, 0, 0));
        inputTahun.setText("uuuuuuuuuuuuuu");
        inputTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTahunActionPerformed(evt);
            }
        });
        PanelInput.add(inputTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 240, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setText("Tahun");
        PanelInput.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 140, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel3.setText("Bulan");
        PanelInput.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 100, 40));

        getContentPane().add(PanelInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 750, 160));

        PanelOutput.setBackground(new java.awt.Color(255, 102, 102));
        PanelOutput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        outTanggal.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        outTanggal.setText("Output di sini..");
        PanelOutput.add(outTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 650, 40));

        getContentPane().add(PanelOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 750, 130));

        PanelButt.setBackground(new java.awt.Color(255, 204, 204));
        PanelButt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttKeluar.setBackground(new java.awt.Color(255, 51, 51));
        buttKeluar.setForeground(new java.awt.Color(0, 0, 0));
        buttKeluar.setText("Keluar");
        buttKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttKeluarActionPerformed(evt);
            }
        });
        PanelButt.add(buttKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 170, -1));

        buttHitung.setBackground(new java.awt.Color(255, 51, 51));
        buttHitung.setForeground(new java.awt.Color(0, 0, 0));
        buttHitung.setText("Hitung");
        buttHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttHitungActionPerformed(evt);
            }
        });
        PanelButt.add(buttHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 170, -1));

        buttDel.setBackground(new java.awt.Color(255, 51, 51));
        buttDel.setForeground(new java.awt.Color(0, 0, 0));
        buttDel.setText("Hapus");
        buttDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttDelActionPerformed(evt);
            }
        });
        PanelButt.add(buttDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 170, -1));

        buttSimpan.setBackground(new java.awt.Color(255, 51, 51));
        buttSimpan.setForeground(new java.awt.Color(0, 0, 0));
        buttSimpan.setText("Simpan");
        buttSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttSimpanActionPerformed(evt);
            }
        });
        PanelButt.add(buttSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 170, -1));

        getContentPane().add(PanelButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 750, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttDelActionPerformed
        inputTahun.setText("");
        boxBulan.setSelectedIndex(0);
        outTanggal.setText("");
        inputTahun.requestFocus();
    }//GEN-LAST:event_buttDelActionPerformed

    private void inputTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTahunActionPerformed

    private void boxBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxBulanActionPerformed

    private void buttHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttHitungActionPerformed
        try {
            String tahunStr = inputTahun.getText().trim();
            if (tahunStr.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Tahun tidak boleh kosong!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int tahun = Integer.parseInt(tahunStr);
            String bulan = boxBulan.getSelectedItem().toString();
            
            HitungHari hitungHari = new HitungHari();
            int jumlahHari = hitungHari.hitung(tahun, bulan);
            
            outTanggal.setText("Jumlah hari pada bulan " + bulan + " tahun " + tahun + " adalah " + jumlahHari);
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Input tahun harus berupa angka!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttHitungActionPerformed

    private void buttSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttSimpanActionPerformed
        String hasil = outTanggal.getText();
        
        if (hasil.isEmpty() || hasil.equals("Output di sini..")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Belum ada hasil perhitungan yang bisa disimpan!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try (java.io.BufferedWriter writer = new java.io.BufferedWriter(new java.io.FileWriter("HasilPerhitungan.txt", true))) {
            writer.write(hasil);
            writer.newLine(); 
            javax.swing.JOptionPane.showMessageDialog(this, "Hasil berhasil disimpan ke file 'HasilPerhitungan.txt'!", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (java.io.IOException ex) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal menyimpan file", ex);
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan file!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttSimpanActionPerformed

    private void buttKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PenentuJumlahHari().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelButt;
    private javax.swing.JPanel PanelInput;
    private javax.swing.JPanel PanelOutput;
    private javax.swing.JComboBox<String> boxBulan;
    private javax.swing.JButton buttDel;
    private javax.swing.JButton buttHitung;
    private javax.swing.JButton buttKeluar;
    private javax.swing.JButton buttSimpan;
    private javax.swing.JTextField inputTahun;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel outTanggal;
    // End of variables declaration//GEN-END:variables
}
