/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kalkulator;

/**
 *
 * @author stevedownes
 */
public class Kalkulator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Kalkulator.class.getName());
    
    double NumEnter1;
    double NumEnter2;
    double Result;
    String Op;
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtResult = new javax.swing.JTextField();
        no9 = new javax.swing.JButton();
        no7 = new javax.swing.JButton();
        no8 = new javax.swing.JButton();
        no6 = new javax.swing.JButton();
        no4 = new javax.swing.JButton();
        no5 = new javax.swing.JButton();
        no3 = new javax.swing.JButton();
        no1 = new javax.swing.JButton();
        no2 = new javax.swing.JButton();
        buttDesim = new javax.swing.JButton();
        no0 = new javax.swing.JButton();
        buttClear = new javax.swing.JButton();
        buttJumlah = new javax.swing.JButton();
        buttKurang = new javax.swing.JButton();
        buttKali = new javax.swing.JButton();
        buttBagi = new javax.swing.JButton();
        buttEqual = new javax.swing.JButton();
        buttPersen = new javax.swing.JButton();
        buttBackSpace = new javax.swing.JButton();
        buttOFF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtResult.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jtxtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtResultActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 560, 70));

        no9.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        no9.setText("9");
        no9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no9ActionPerformed(evt);
            }
        });
        getContentPane().add(no9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 80, 70));

        no7.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        no7.setText("7");
        no7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no7ActionPerformed(evt);
            }
        });
        getContentPane().add(no7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 80, 70));

        no8.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        no8.setText("8");
        no8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no8ActionPerformed(evt);
            }
        });
        getContentPane().add(no8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 80, 70));

        no6.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        no6.setText("6");
        no6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no6ActionPerformed(evt);
            }
        });
        getContentPane().add(no6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 80, 70));

        no4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        no4.setText("4");
        no4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no4ActionPerformed(evt);
            }
        });
        getContentPane().add(no4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, 70));

        no5.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        no5.setText("5");
        no5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no5ActionPerformed(evt);
            }
        });
        getContentPane().add(no5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 80, 70));

        no3.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        no3.setText("3");
        no3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no3ActionPerformed(evt);
            }
        });
        getContentPane().add(no3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 80, 70));

        no1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        no1.setText("1");
        no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no1ActionPerformed(evt);
            }
        });
        getContentPane().add(no1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 80, 70));

        no2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        no2.setText("2");
        no2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no2ActionPerformed(evt);
            }
        });
        getContentPane().add(no2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 80, 70));

        buttDesim.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        buttDesim.setText(".");
        buttDesim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttDesimActionPerformed(evt);
            }
        });
        getContentPane().add(buttDesim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 80, 70));

        no0.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        no0.setText("0");
        no0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no0ActionPerformed(evt);
            }
        });
        getContentPane().add(no0, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 80, 70));

        buttClear.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        buttClear.setText("C");
        buttClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttClearActionPerformed(evt);
            }
        });
        getContentPane().add(buttClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 80, 70));

        buttJumlah.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        buttJumlah.setText("+");
        buttJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttJumlahActionPerformed(evt);
            }
        });
        getContentPane().add(buttJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 80, 70));

        buttKurang.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        buttKurang.setText("-");
        buttKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttKurangActionPerformed(evt);
            }
        });
        getContentPane().add(buttKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 80, 70));

        buttKali.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        buttKali.setText("X");
        buttKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttKaliActionPerformed(evt);
            }
        });
        getContentPane().add(buttKali, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 80, 70));

        buttBagi.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        buttBagi.setText("/");
        buttBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttBagiActionPerformed(evt);
            }
        });
        getContentPane().add(buttBagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 80, 70));

        buttEqual.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        buttEqual.setText("=");
        buttEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttEqualActionPerformed(evt);
            }
        });
        getContentPane().add(buttEqual, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 80, 70));

        buttPersen.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        buttPersen.setText("%");
        buttPersen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttPersenActionPerformed(evt);
            }
        });
        getContentPane().add(buttPersen, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 80, 70));

        buttBackSpace.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        buttBackSpace.setText("B");
        buttBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttBackSpaceActionPerformed(evt);
            }
        });
        getContentPane().add(buttBackSpace, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 80, 70));

        buttOFF.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        buttOFF.setText("OFF");
        buttOFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttOFFActionPerformed(evt);
            }
        });
        getContentPane().add(buttOFF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 80, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterAngka(String karakter){
        String Nums = jtxtResult.getText() + karakter;
        jtxtResult.setText(Nums);
    }
    
    private void no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no1ActionPerformed
        enterAngka("1");
    }//GEN-LAST:event_no1ActionPerformed

    private void no2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no2ActionPerformed
        enterAngka("2");
    }//GEN-LAST:event_no2ActionPerformed

    private void no9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no9ActionPerformed
        enterAngka("9");
    }//GEN-LAST:event_no9ActionPerformed

    private void buttDesimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttDesimActionPerformed
        if(!jtxtResult.getText().contains(".")){
            jtxtResult.setText(jtxtResult.getText() + buttDesim.getText());
        }
    }//GEN-LAST:event_buttDesimActionPerformed

    private void buttClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttClearActionPerformed
        jtxtResult.setText("");
        
        String Fn, Sn;
        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);
        
        Fn = "";
        Sn = "";
    }//GEN-LAST:event_buttClearActionPerformed

    private void buttJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttJumlahActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "+";
    }//GEN-LAST:event_buttJumlahActionPerformed

    private void buttEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttEqualActionPerformed
        if (!jtxtResult.getText().isEmpty() && Op != null) {
            NumEnter2 = Double.parseDouble(jtxtResult.getText());
            
            if(Op.equals("+")){
                Result = NumEnter1 + NumEnter2;
            } else if(Op.equals("-")){
                Result = NumEnter1 - NumEnter2;
            } else if(Op.equals("X")){ 
                Result = NumEnter1 * NumEnter2;
            } else if(Op.equals("/")){
                if(NumEnter2 != 0) {
                    Result = NumEnter1 / NumEnter2;
                } else {
                    jtxtResult.setText("Error");
                    return;
                }
            }
            
            if (Result % 1 == 0) {
                jtxtResult.setText(String.valueOf((int) Result));
            } else {
                jtxtResult.setText(String.valueOf(Result));
            }
            NumEnter1 = Result;
        }
    }//GEN-LAST:event_buttEqualActionPerformed

    private void no7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no7ActionPerformed
        enterAngka("7");
    }//GEN-LAST:event_no7ActionPerformed

    private void no3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no3ActionPerformed
        enterAngka("3");
    }//GEN-LAST:event_no3ActionPerformed

    private void no4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no4ActionPerformed
        enterAngka("4");
    }//GEN-LAST:event_no4ActionPerformed

    private void no5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no5ActionPerformed
        enterAngka("5");
    }//GEN-LAST:event_no5ActionPerformed

    private void no6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no6ActionPerformed
        enterAngka("6");
    }//GEN-LAST:event_no6ActionPerformed

    private void no8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no8ActionPerformed
        enterAngka("8");
    }//GEN-LAST:event_no8ActionPerformed

    private void no0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no0ActionPerformed
        enterAngka("0");
    }//GEN-LAST:event_no0ActionPerformed

    private void jtxtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtResultActionPerformed

    private void buttBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttBagiActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "/";
    }//GEN-LAST:event_buttBagiActionPerformed

    private void buttKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttKaliActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "X";
    }//GEN-LAST:event_buttKaliActionPerformed

    private void buttKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttKurangActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "-";
    }//GEN-LAST:event_buttKurangActionPerformed

    private void buttPersenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttPersenActionPerformed
        if (!jtxtResult.getText().isEmpty()) {
            double value = Double.parseDouble(jtxtResult.getText());
            jtxtResult.setText(String.valueOf(value / 100));
        }
    }//GEN-LAST:event_buttPersenActionPerformed

    private void buttOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttOFFActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttOFFActionPerformed

    private void buttBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttBackSpaceActionPerformed
        String teks = jtxtResult.getText();
        if (!teks.isEmpty()) {
            jtxtResult.setText(teks.substring(0, teks.length() - 1));
        }
    }//GEN-LAST:event_buttBackSpaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Kalkulator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttBackSpace;
    private javax.swing.JButton buttBagi;
    private javax.swing.JButton buttClear;
    private javax.swing.JButton buttDesim;
    private javax.swing.JButton buttEqual;
    private javax.swing.JButton buttJumlah;
    private javax.swing.JButton buttKali;
    private javax.swing.JButton buttKurang;
    private javax.swing.JButton buttOFF;
    private javax.swing.JButton buttPersen;
    private javax.swing.JTextField jtxtResult;
    private javax.swing.JButton no0;
    private javax.swing.JButton no1;
    private javax.swing.JButton no2;
    private javax.swing.JButton no3;
    private javax.swing.JButton no4;
    private javax.swing.JButton no5;
    private javax.swing.JButton no6;
    private javax.swing.JButton no7;
    private javax.swing.JButton no8;
    private javax.swing.JButton no9;
    // End of variables declaration//GEN-END:variables
}
